# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quran.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


page = 1
# imageShow = "images/" + str(page) + ".png"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        print(page)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.limageFrame = QtWidgets.QLabel(self.centralwidget)
        self.limageFrame.setGeometry(QtCore.QRect(50, 20, 471, 701))
        self.limageFrame.setText("")
        self.limageFrame.setPixmap(QtGui.QPixmap("images/" + str(page) + ".png"))
        self.limageFrame.setScaledContents(True)
        self.limageFrame.setObjectName("limageFrame")

        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(670, 640, 88, 34))
        self.prevButton.setObjectName("prevButton")
        
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(560, 640, 88, 34))
        self.nextButton.setObjectName("nextButton")
        
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(620, 730, 181, 31))
        self.versionLabel.setObjectName("versionLabel")

        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(660, 590, 101, 32))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setRange(1, 604)
        self.spinBox.valueChanged.connect(self.spinPage)

        self.textJuz = QtWidgets.QLabel(self.centralwidget)
        self.textJuz.setGeometry(QtCore.QRect(560, 530, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textJuz.setFont(font)
        self.textJuz.setObjectName("textJuz")
        self.spinJuz = QtWidgets.QSpinBox(self.centralwidget)
        self.spinJuz.setGeometry(QtCore.QRect(660, 530, 101, 32))
        self.spinJuz.setObjectName("spinJuz")
        self.spinJuz.setRange(1, 30)
        self.spinJuz.valueChanged.connect(self.jumpJuz)
        

        self.textPage = QtWidgets.QLabel(self.centralwidget)
        self.textPage.setGeometry(QtCore.QRect(560, 590, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textPage.setFont(font)
        self.textPage.setObjectName("textPage")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.nextButton.clicked.connect(self.nextPage)
        self.prevButton.clicked.connect(self.prevPage)

    def listSurah(self):
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 120, 231, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Al - Fatihah")
        self.comboBox.addItem("Al - Baqarah")
        self.comboBox.addItem("Ali 'Imran")
        self.comboBox.addItem("An - Nisa'")
        self.comboBox.addItem("Al - Ma' idah")
        self.comboBox.addItem("Al - An 'am")
        self.comboBox.addItem("Al - A'raf")
        self.comboBox.addItem("Al - Anfal")
        self.comboBox.addItem("At - Taubah")
        self.comboBox.addItem("Yunus")
        self.comboBox.addItem("Hud")
        self.comboBox.addItem("Ar - Ra'd")
        self.comboBox.addItem("Ibrahim")
        self.comboBox.addItem("Al - Hijr")
        self.comboBox.addItem("Al - Nahl")
        self.comboBox.addItem("Al - Isra'")
        self.comboBox.addItem("Al - Kahf")
        self.comboBox.addItem("Maryam")
        self.comboBox.addItem("Taha")
        self.comboBox.addItem("Al - Anbiya'")
        self.comboBox.addItem("Al - Hajj")
        self.comboBox.addItem("Al - Mu'minun")
        self.comboBox.addItem("An - Nur")
        self.comboBox.addItem("Al - Furqan")
        self.comboBox.addItem("Asy - Syu'ara")
        self.comboBox.addItem("An - Naml")
        self.comboBox.addItem("Al - Qasas")
        self.comboBox.addItem("Al - Ankabut")
        self.comboBox.addItem("Ar - Rum")
        self.comboBox.addItem("Luqman")
        self.comboBox.addItem("As - Sajadah")
        self.comboBox.addItem("Al - Ahzab")
        self.comboBox.addItem("Saba'")
        self.comboBox.addItem("Fatir")
        self.comboBox.addItem("Yasin")
        self.comboBox.addItem("As - Saffat")
        self.comboBox.addItem("Sad")
        self.comboBox.addItem("Az- Zumar")
        self.comboBox.addItem("Al - Mu'min")
        self.comboBox.addItem("Fussilat")
        self.comboBox.addItem("Asy - Syura")
        self.comboBox.addItem("Az - Zukhruf")
        self.comboBox.addItem("Ad - Dukhan")
        self.comboBox.addItem("Al - Jasiyah")
        self.comboBox.addItem("Al - Ahqaf")
        self.comboBox.addItem("Muhammad")
        self.comboBox.addItem("At - Fath")
        self.comboBox.addItem("Al - Hujurat")
        self.comboBox.addItem("Qaf")
        self.comboBox.addItem("Az - Zariyat")
        self.comboBox.addItem("At - Tur")
        self.comboBox.addItem("An - Najm")
        self.comboBox.addItem("Al - Qamar")
        self.comboBox.addItem("Ar - Rahman")
        self.comboBox.addItem("Al - Waqi'ah")
        self.comboBox.addItem("Al Hadid")
        self.comboBox.addItem("Al - Mujadilah")
        self.comboBox.addItem("Al - Hasyr")
        self.comboBox.addItem("Al - Mumtahanah")
        self.comboBox.addItem("As - Saff")
        self.comboBox.addItem("Al - Jumu'ah")
        self.comboBox.addItem("Al - Munafiqun")
        self.comboBox.addItem("At - Tagabun")
        self.comboBox.addItem("At - Talaq")
        self.comboBox.addItem("At - Tahrim")
        self.comboBox.addItem("Al - Mulk")
        self.comboBox.addItem("Al - Qalam")
        self.comboBox.addItem("Al - Haqqah")
        self.comboBox.addItem("Al - Ma'arij")
        self.comboBox.addItem("Nuh")
        self.comboBox.addItem("Al - Jinn")
        self.comboBox.addItem("Al - Muzzammil")
        self.comboBox.addItem("Al - Muddassir")
        self.comboBox.addItem("As - Qiyamah")
        self.comboBox.addItem("Al - Insan")
        self.comboBox.addItem("Al - Mursalat")
        self.comboBox.addItem("An - Naba'")
        self.comboBox.addItem("An - Nazi'at")
        self.comboBox.addItem("'Abasa")
        self.comboBox.addItem("At - Takwir")
        self.comboBox.addItem("Al - Infitar")
        self.comboBox.addItem("At - Tatfif")
        self.comboBox.addItem("Al - Insyiqaq")
        self.comboBox.addItem("Al - Buruj")
        self.comboBox.addItem("At - Tariq")
        self.comboBox.addItem("Al - A'la")
        self.comboBox.addItem("Al - Gasyiyah")
        self.comboBox.addItem("Al - Fajr")
        self.comboBox.addItem("Al - Balad")
        self.comboBox.addItem("Asy - Syams")
        self.comboBox.addItem("Al - Lail")
        self.comboBox.addItem("Ad- Dhuha")
        self.comboBox.addItem("Al - Insyirah")
        self.comboBox.addItem("At - Tin")
        self.comboBox.addItem("Al - 'Alaq")
        self.comboBox.addItem("At - Qadr")
        self.comboBox.addItem("Al - Bayyinah")
        self.comboBox.addItem("Al - Zalzalah")
        self.comboBox.addItem("Al - 'Adiyat")
        self.comboBox.addItem("Al - Qari'ah")
        self.comboBox.addItem("At - Takatsur")
        self.comboBox.addItem("Al - Asr")
        self.comboBox.addItem("Al - Humazah")
        self.comboBox.addItem("Al - Fill")
        self.comboBox.addItem("Al - Quraisy")
        self.comboBox.addItem("Al - Ma'un")
        self.comboBox.addItem("Al Kautsar")
        self.comboBox.addItem("Al - Kafirun")
        self.comboBox.addItem("An - Nasr")
        self.comboBox.addItem("Al - Lahab")
        self.comboBox.addItem("Al - Ikhlas")
        self.comboBox.addItem("Al - Falaq")
        self.comboBox.addItem("An - Nass")


    def nextPage(self):
        global page
        if page < 604:
            page = page + 1
        self.spinBox.setValue(page)
        imageShow = "images/" + str(page) + ".png"
        self.limageFrame.setPixmap(QtGui.QPixmap(imageShow))
        print("nextPage" + imageShow)

    def prevPage(self):
        global page
        if page > 1:
            page = page - 1
        self.spinBox.setValue(page)
        imageShow = "images/" + str(page) + ".png"
        self.limageFrame.setPixmap(QtGui.QPixmap(imageShow))
        print("prevPage" + imageShow)

    def spinPage(self):
        global page
        page = self.spinBox.value()
        imageShow = "images/" + str(page) + ".png"
        self.limageFrame.setPixmap(QtGui.QPixmap(imageShow))
        print("spinPage" + imageShow)

    def jumpJuz(self):
        juz = self.spinJuz.value()
        page = (juz - 1) * 20 + 2 
        imageShow = "images/" + str(page) + ".png"
        self.spinBox.setValue(page)
        self.limageFrame.setPixmap(QtGui.QPixmap(imageShow))
        print("jumpPage" + imageShow)
        #self.spinJuz.setValue(((page-1)-2)/20)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Al - Qur'an (PyQt5)"))
        self.prevButton.setText(_translate("MainWindow", "Prev. Page >"))
        self.nextButton.setText(_translate("MainWindow", "< Next Page"))
        self.versionLabel.setText(_translate("MainWindow", "very alpha version : 0.0.10"))
        self.textPage.setText(_translate("MainWindow", "Page :"))
        self.textJuz.setText(_translate("MainWindow", "Juz :"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
